### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by colesnicov** [stm32duino/FatFs#1]
Hello. Is it possible to add code to use example? Just SD, SPI FLASH and RTC? Take a question, what about RAM?

**Comment by fpistm** [comment]
Hi @colesnicov,
sorry for the delay, I missed the notification.
This library is used by the https://github.com/stm32duino/STM32SD library.
I only use it for SD. Don't know about SPI FLASH.
What about RTC?

**Comment by colesnicov** [comment]
Hi. What about RTC from [http://elm-chan.org/fsw/ff](http://elm-chan.org/fsw/ff/00index_e.html) : http://elm-chan.org/fsw/ff/res/layers.png I'm just interested in it. I did not read the documentation, I did not find the pages yet
