### ISSUE TITLE
ffconf_template.h cannot find cmsis_os.h

### ISSUE THREAD

**Issue by RichardB01** [stm32duino/FatFs#5]
Hi,

I'm trying to use this library but when i compile it, i receive this error: 

ffconf_template.h: 290:10: fatal error: cmsis_os.h: No such file or directory
   290 | #include "cmsis_os.h"
   |          ^~~~~~~~~~~~
   compilation terminated

What should i do to fix this?

**Comment by RichardB01** [comment]
@fpistm  Hi i'm not sure if you will notice this issue so i tagged you in it :)

**Comment by fpistm** [comment]
How do you use this library?

**Comment by RichardB01** [comment]
I just include these headers

> #include <SdFatFs.h>
> #include <Sd2Card.h>
> #include <ffconf_default_68300.h>
> #include <ffconf_default_32020.h>
> #include <ffconf.h>
> #include <bsp_sd.h>
> #include <integer.h>
> #include <ff_gen_drv.h>
> #include <ffconf_template.h>
> #include <ff.h>
> #include <FatFs.h>
> #include <diskio.h>

It seems like there is a file "cmsis_os.h" missing from the stm32duino file tree?
ffconf_tempate.h Line 290:
#include "C:\Users\Richa\AppData\Local\arduino15\packages\STM32\tools\CMSIS\5.5.1\CMSIS\RTOS\RTX\INC\cmsis_os.h"

I can fix it by hardcoding the path to the cmsis_os.h and that fixes it:

And also there are some errors with bsp_sd.h, you need to include this header to get the correct typedefs 
#include "stm32l4xx_hal_sd.h"

**Comment by fpistm** [comment]
It works fine with the STM32SD, I don't know exactly what you try to achieve.
Moreover, I saw L4....
so please be really precise in your description... which board you use, Core version, libraries installed and used,...
As far as I know there is no L4 board with SDCARD supported....

**Comment by RichardB01** [comment]
Ah ok that makes sense, then how do i interface with an external micro sd?

**Comment by RichardB01** [comment]
So i can just use the normal Arduino SD library if i'm using an external sd card component? this one? https://www.arduino.cc/en/reference/SD

**Comment by fpistm** [comment]
Seriously?
How is connected you SDCard slot?
SPI? SDIO?

There is a difference btw SD.h from Arduino which use SPI to access SD.
And the STM32SD.h which uses the SDIO or SDMMC interface to access the SD....

Moreover FatFS is for the STM32SD library and does not support the SD from Arduino (over SPI).
