### ISSUE TITLE
ExFAT capabilities?

### ISSUE THREAD

**Issue by RichardB01** [stm32duino/FatFs#8]
I'm struggling to get this library to work with ExFAT, I suspect that the fatfs version 0.12c is missing many fixes to the ExFAT implementation.

The cards version 0.12c is quite outdated. 7 versions behind the current 0.14b version. 

Is there any way I can update this library to 0.14b?

Thanks

**Comment by fpistm** [comment]
Hi @Bambofy 
This library is based on release available here: https://github.com/STMicroelectronics/stm32_mw_fatfs
It is only to provide it as an Arduino library format.
I understand it is quite outdated but while there is no new release I could not update.
You should ask to https://github.com/STMicroelectronics/stm32_mw_fatfs repo a new release.
